name: taggo
description: A new Flutter project with Firebase + Google Sign In + GetX routing

publish_to: "none" # Remove nếu muốn public lên pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0

  # Google Sign-In
  google_sign_in: ^6.2.1

  # State management & navigation
  get: ^4.6.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
