// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKc_3anLcKIcS30QoqOvwRzsHPNUnEoLs',
    appId: '1:663171440806:android:526a35f44974d04d3e1467',
    messagingSenderId: '663171440806',
    projectId: 'tag-go-d69f5',
    storageBucket: 'tag-go-d69f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA67qAQ3tG0KFMux_x8MPoaWm1k7UM9obU',
    appId: '1:663171440806:ios:6b8617eebf29021d3e1467',
    messagingSenderId: '663171440806',
    projectId: 'tag-go-d69f5',
    storageBucket: 'tag-go-d69f5.firebasestorage.app',
    androidClientId: '663171440806-qaa7q7b12hpjgputuql3j1629ki8h7br.apps.googleusercontent.com',
    iosClientId: '663171440806-7fjsr3qvj8tshpj0odheh3fof9b9v41n.apps.googleusercontent.com',
    iosBundleId: 'com.example.tagGoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA67qAQ3tG0KFMux_x8MPoaWm1k7UM9obU',
    appId: '1:663171440806:ios:6b8617eebf29021d3e1467',
    messagingSenderId: '663171440806',
    projectId: 'tag-go-d69f5',
    storageBucket: 'tag-go-d69f5.firebasestorage.app',
    androidClientId: '663171440806-qaa7q7b12hpjgputuql3j1629ki8h7br.apps.googleusercontent.com',
    iosClientId: '663171440806-7fjsr3qvj8tshpj0odheh3fof9b9v41n.apps.googleusercontent.com',
    iosBundleId: 'com.example.tagGoApp',
  );
}
